ci: commented owasp plugin to test

diff --git a/.github/workflows/android_ci.yml b/.github/workflows/android_ci.yml
--- a/.github/workflows/android_ci.yml
+++ b/.github/workflows/android_ci.yml
@@ -38,15 +38,15 @@ jobs:
       - name: Grant Execute Permissions
         run: chmod +x gradlew
 
-      - name: Run OWASP Dependency Check
-        run: ./gradlew dependencyCheckAnalyze --info --no-daemon || echo "OWASP check failed, continuing..."
+      #- name: Run OWASP Dependency Check
+      #  run: ./gradlew dependencyCheckAnalyze --info --no-daemon || echo "OWASP check failed, continuing..."
       
-      - name: Upload OWASP Report
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: owasp-report
-          path: app/build/reports/dependency-check-report.html
+      # - name: Upload OWASP Report
+      #  if: always()
+      #  uses: actions/upload-artifact@v4
+      #  with:
+      #    name: owasp-report
+      #    path: app/build/reports/dependency-check-report.html
 
       - name: Run Unit Tests
         run: ./gradlew testDebugUnitTest --no-daemon || true
